### ISSUE TITLE
Identify wireless interfaces

### ISSUE THREAD

**Issue by DeadPackets** [DeadPackets/HackPi#2]
This is a problem because I cant know which interface is which WiFi card, and I want to use the ALFA specifically for jamming and the smaller edimax ones for small range things like sniffing and cracking.

Their mac address seems to work just fine to identify them, just how do I do that in Node?

**Comment by shadowblade7536** [comment]
After implementing MacChanger, this has become harder to do, unless we use macchanger itself. Ill see if I could process output from macchanger to identify the original vendor.

**Comment by DeadPackets** [comment]
This could help https://www.npmjs.com/package/oui

**Comment by DeadPackets** [comment]
Oui package actually helps fix this issue, I just hope it doesnt need an upstream WiFi connection
