### ISSUE TITLE
Keep track of everything (Running attacks, status of interfaces)

### ISSUE THREAD

**Issue by DeadPackets** [DeadPackets/HackPi#3]
This could be a problem if the server wont remember that it launched a DoS attack on a certain wireless point using a certain interface, and then we try to call another function on that same interface.

We should have a global kind of way of tracking EVERYTHING so that if an interface is busy, it can be marked as so and the option for disabling the running process should be there to, which means we need to track both the status of interfaces and their respective jobs. (wlan0 is ddosing, wlan1 is scanning, wlan2 is down, so on)

**Comment by shadowblade7536** [comment]
We only need to track wireless interfaces, so maybe a global array of objects that contain statuses of wireless cards should work? Will test to see if this works. Also, to identify wireless cards only, I have decided to use the node module `wireless-tools/ifconfig` instead of using `os`.

**Comment by shadowblade7536** [comment]
I have added an example idea of how the global tracking array should work. Ill need to make a fully functional WebUI before attempting to try out anything. Need to stabalize things.

**Comment by DeadPackets** [comment]
Finally done with this! Added a global tracking array with a `status` value!
